table Vendas
	lineageTag: 7951376f-4af3-4d92-990a-ed7de8580621

	measure 'Total de Vendas' = CALCULATE(SUM(Vendas[Valor]), Vendas[Valor] > 0)
		formatString: 0
		lineageTag: df83b620-6364-432b-98ef-255fff675e40

	column Produto
		dataType: string
		lineageTag: eecc65cc-7134-4b82-9745-d06fbca0b952
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: int64
		formatString: 0
		lineageTag: 37498165-4559-4e87-8736-23619c82c256
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8ssvSU3Kz89W0lEyNjUwUIrViVbyzS8tTgUKWEC4IanJOYkp+UABI1OgSCwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Produto = _t, Valor = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Produto", type text}, {"Valor", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

